### ISSUE TITLE
Targeting .Net Standard

### ISSUE THREAD

**Issue by MarkWillems** [FireStack-Lab/LaksaCsharp#1]
Hi,

I saw the project is targeting Framework v4.5.2, is there a reason not to target .NET Standard?

**Comment by yanbin007** [comment]
Ok,
I have changed the target framework to  .Net Standard，please update the code. And I created  a new branch for .Net Framework, If anyone needs it.
Thanks

**Comment by MarkWillems** [comment]
👍
